/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    destinations: Destination;
    'experience-categories': ExperienceCategory;
    experiences: Experience;
    reviews: Review;
    bookings: Booking;
    customers: Customer;
    coupons: Coupon;
    events: Event;
    posts: Post;
    pages: Page;
    'newsletter-subscribers': NewsletterSubscriber;
    'corporate-enquiries': CorporateEnquiry;
    'custom-trip-requests': CustomTripRequest;
    'travel-service-requests': TravelServiceRequest;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    destinations: DestinationsSelect<false> | DestinationsSelect<true>;
    'experience-categories': ExperienceCategoriesSelect<false> | ExperienceCategoriesSelect<true>;
    experiences: ExperiencesSelect<false> | ExperiencesSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    bookings: BookingsSelect<false> | BookingsSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    coupons: CouponsSelect<false> | CouponsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'newsletter-subscribers': NewsletterSubscribersSelect<false> | NewsletterSubscribersSelect<true>;
    'corporate-enquiries': CorporateEnquiriesSelect<false> | CorporateEnquiriesSelect<true>;
    'custom-trip-requests': CustomTripRequestsSelect<false> | CustomTripRequestsSelect<true>;
    'travel-service-requests': TravelServiceRequestsSelect<false> | TravelServiceRequestsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | 'en' | 'en'[];
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Determines what this staff member can access across the admin.
   */
  roles: ('super-admin' | 'operations' | 'content-editor' | 'event-manager' | 'finance' | 'checkin')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for screen readers and SEO.
   */
  alt: string;
  /**
   * Optional photographer / source credit.
   */
  credit?: string | null;
  /**
   * Loose grouping for the media library (Accra, Volta, Hiking, …).
   */
  category?:
    | (
        | 'accra'
        | 'cape-coast'
        | 'volta'
        | 'eastern-region'
        | 'hiking'
        | 'cycling'
        | 'corporate'
        | 'events'
        | 'food'
        | 'people'
        | 'other'
      )
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "destinations".
 */
export interface Destination {
  id: number;
  title: string;
  /**
   * URL path segment. Leave blank to auto-generate from "title".
   */
  slug?: string | null;
  region:
    | 'Greater Accra'
    | 'Central Region'
    | 'Volta Region'
    | 'Eastern Region'
    | 'Ashanti Region'
    | 'Western Region'
    | 'Northern Region'
    | 'Other';
  /**
   * Show on the homepage "Explore Ghana" section.
   */
  featured?: boolean | null;
  heroImage?: (number | null) | Media;
  shortDescription?: string | null;
  whyVisit?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  thingsToDo?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  bestTimeToVisit?: string | null;
  travelTips?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Search & social preview. Leave blank to inherit from the page content.
   */
  meta?: {
    /**
     * Overrides the <title>. ~60 characters.
     */
    title?: string | null;
    /**
     * Meta description / social preview. ~155 characters.
     */
    description?: string | null;
    /**
     * Open Graph / social share image (1200×630).
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experience-categories".
 */
export interface ExperienceCategory {
  id: number;
  title: string;
  /**
   * URL path segment. Leave blank to auto-generate from "title".
   */
  slug?: string | null;
  /**
   * One-line summary shown under the title.
   */
  blurb?: string | null;
  /**
   * lucide-react icon name, e.g. "Mountain".
   */
  icon?: string | null;
  image?: (number | null) | Media;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experiences".
 */
export interface Experience {
  id: number;
  title: string;
  shortDescription?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  highlights?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  whoFor?: string | null;
  itinerary?:
    | {
        time?: string | null;
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  included?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  excluded?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  whatToBring?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  pricingStrategy: 'fixed' | 'tiered' | 'per-group' | 'private' | 'quote';
  /**
   * Whole Cedi. Shown as the card / "from" price.
   */
  priceFrom: number;
  /**
   * Per-person price by group size. Leave blank to inherit the from price.
   */
  priceTiers?:
    | {
        minGuests: number;
        maxGuests?: number | null;
        /**
         * GHS
         */
        pricePerPerson?: number | null;
        requestQuote?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * GHS per group
   */
  privatePrice?: number | null;
  /**
   * Disabled by default. Capital Pulse's GHS 1,400 is the international rate (§34); enable once Trivoxo supplies resident prices.
   */
  visitorPricing?: {
    enabled?: boolean | null;
    residentPrice?: number | null;
  };
  availabilityType: 'everyday' | 'weekdays' | 'specific-dates' | 'on-request' | 'private-only';
  /**
   * e.g. Dodi Island runs Sat + Sun only (§36).
   */
  weekdays?: ('mon' | 'tue' | 'wed' | 'thu' | 'fri' | 'sat' | 'sun')[] | null;
  includePublicHolidays?: boolean | null;
  minGuests?: number | null;
  maxGuests?: number | null;
  minNoticeHours?: number | null;
  maxAdvanceDays?: number | null;
  /**
   * Mark the whole experience as sold out.
   */
  soldOut?: boolean | null;
  duration?: string | null;
  difficulty?: ('easy' | 'moderate' | 'challenging') | null;
  meetingPoint?: string | null;
  pickupInfo?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  /**
   * Optional metadata that varies by activity type (§31).
   */
  activityDetails?: {
    distanceKm?: number | null;
    elevationM?: number | null;
    terrain?: string | null;
    fitnessNote?: string | null;
    equipmentProvided?: string | null;
    minimumAge?: number | null;
    mealIncluded?: boolean | null;
  };
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Search & social preview. Leave blank to inherit from the page content.
   */
  meta?: {
    /**
     * Overrides the <title>. ~60 characters.
     */
    title?: string | null;
    /**
     * Meta description / social preview. ~155 characters.
     */
    description?: string | null;
    /**
     * Open Graph / social share image (1200×630).
     */
    image?: (number | null) | Media;
  };
  /**
   * URL path segment. Leave blank to auto-generate from "title".
   */
  slug?: string | null;
  category?: (number | null) | ExperienceCategory;
  destination?: (number | null) | Destination;
  badge?: ('bestseller' | 'new' | 'popular' | 'limited') | null;
  /**
   * Surface in "Popular Experiences" on the homepage.
   */
  featured?: boolean | null;
  /**
   * Leave blank until real review data exists.
   */
  rating?: number | null;
  reviewCount?: number | null;
  heroImage?: (number | null) | Media;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  title: string;
  body: string;
  rating: number;
  authorName: string;
  travellerType?: ('solo' | 'couples' | 'friends' | 'family' | 'corporate') | null;
  experience?: (number | null) | Experience;
  status?: ('pending' | 'approved' | 'rejected') | null;
  /**
   * Linked to a completed booking.
   */
  verified?: boolean | null;
  bookingReference?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings".
 */
export interface Booking {
  id: number;
  /**
   * Auto-generated, e.g. TVX-26-A8F41.
   */
  reference?: string | null;
  status:
    | 'draft'
    | 'held'
    | 'pending_payment'
    | 'paid'
    | 'confirmed'
    | 'in_progress'
    | 'completed'
    | 'cancelled'
    | 'refund_pending'
    | 'partially_refunded'
    | 'refunded'
    | 'expired'
    | 'no_show';
  source:
    | 'website'
    | 'whatsapp'
    | 'instagram'
    | 'tiktok'
    | 'facebook'
    | 'phone'
    | 'walk-in'
    | 'corporate'
    | 'referral'
    | 'partner'
    | 'other';
  experience: number | Experience;
  customer?: (number | null) | Customer;
  departureDate: string;
  adults?: number | null;
  children?: number | null;
  booker: {
    firstName: string;
    lastName: string;
    email: string;
    phone: string;
    country?: string | null;
    emergencyContact?: string | null;
  };
  pickup?: string | null;
  specialRequest?: string | null;
  dietary?: string | null;
  guests?:
    | {
        name: string;
        category?: ('adult' | 'child' | 'infant') | null;
        id?: string | null;
      }[]
    | null;
  totalAmount?: number | null;
  paymentState?: ('paid' | 'deposit' | 'outstanding') | null;
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  firstName: string;
  lastName: string;
  email: string;
  phone?: string | null;
  country?: string | null;
  marketingOptIn?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons".
 */
export interface Coupon {
  id: number;
  code: string;
  type: 'percentage' | 'fixed';
  value: number;
  appliesTo?: ('all' | 'experiences' | 'events') | null;
  experiences?: (number | Experience)[] | null;
  events?: (number | Event)[] | null;
  minOrder?: number | null;
  validFrom?: string | null;
  validTo?: string | null;
  maxUses?: number | null;
  usedCount?: number | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  shortDescription?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  coverImage?: (number | null) | Media;
  startsAt: string;
  endsAt?: string | null;
  venue?: string | null;
  /**
   * City/area shown to customers, e.g. "Aburi".
   */
  location?: string | null;
  destination?: (number | null) | Destination;
  about?: string | null;
  highlights?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  included?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional long-form alternative to the bullet list above.
   */
  whatToExpect?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  ticketTypes?:
    | {
        name: string;
        price: number;
        quantity?: number | null;
        saleStart?: string | null;
        saleEnd?: string | null;
        perOrderLimit?: number | null;
        soldOut?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Search & social preview. Leave blank to inherit from the page content.
   */
  meta?: {
    /**
     * Overrides the <title>. ~60 characters.
     */
    title?: string | null;
    /**
     * Meta description / social preview. ~155 characters.
     */
    description?: string | null;
    /**
     * Open Graph / social share image (1200×630).
     */
    image?: (number | null) | Media;
  };
  /**
   * URL path segment. Leave blank to auto-generate from "title".
   */
  slug?: string | null;
  /**
   * Show in the homepage "Upcoming events" section.
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  excerpt?: string | null;
  coverImage?: (number | null) | Media;
  /**
   * Structured content blocks — an optional heading plus a paragraph.
   */
  body?:
    | {
        heading?: string | null;
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional long-form alternative to the body blocks above.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Search & social preview. Leave blank to inherit from the page content.
   */
  meta?: {
    /**
     * Overrides the <title>. ~60 characters.
     */
    title?: string | null;
    /**
     * Meta description / social preview. ~155 characters.
     */
    description?: string | null;
    /**
     * Open Graph / social share image (1200×630).
     */
    image?: (number | null) | Media;
  };
  /**
   * URL path segment. Leave blank to auto-generate from "title".
   */
  slug?: string | null;
  category?:
    | (
        | 'things-to-do'
        | 'travel-planning'
        | 'accra'
        | 'cape-coast'
        | 'volta'
        | 'food-culture'
        | 'adventure'
        | 'events'
        | 'corporate-travel'
        | 'nightlife'
      )
    | null;
  relatedDestination?: (number | null) | Destination;
  publishedAt?: string | null;
  /**
   * Eligible for the homepage Ghana Guide section.
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  subtitle?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Search & social preview. Leave blank to inherit from the page content.
   */
  meta?: {
    /**
     * Overrides the <title>. ~60 characters.
     */
    title?: string | null;
    /**
     * Meta description / social preview. ~155 characters.
     */
    description?: string | null;
    /**
     * Open Graph / social share image (1200×630).
     */
    image?: (number | null) | Media;
  };
  /**
   * URL path segment. Leave blank to auto-generate from "title".
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscribers".
 */
export interface NewsletterSubscriber {
  id: number;
  email: string;
  /**
   * Where they subscribed, e.g. homepage-footer.
   */
  source?: string | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "corporate-enquiries".
 */
export interface CorporateEnquiry {
  id: number;
  pipelineStatus?:
    | (
        | 'new'
        | 'contacted'
        | 'consultation'
        | 'proposal-preparation'
        | 'proposal-sent'
        | 'negotiation'
        | 'awaiting-deposit'
        | 'confirmed'
        | 'in-progress'
        | 'completed'
        | 'lost'
      )
    | null;
  eventType:
    | 'conference'
    | 'corporate-retreat'
    | 'company-outing'
    | 'team-building'
    | 'product-launch'
    | 'private-event'
    | 'other';
  organisation?: string | null;
  expectedGuests?: number | null;
  preferredDate?: string | null;
  durationDays?: number | null;
  location?: string | null;
  budget?: string | null;
  services?:
    | (
        | 'venue'
        | 'catering'
        | 'transport'
        | 'hotel'
        | 'av'
        | 'photography'
        | 'branding'
        | 'registration'
        | 'entertainment'
        | 'security'
        | 'logistics'
        | 'event-staffing'
      )[]
    | null;
  contact: {
    name: string;
    email: string;
    phone: string;
  };
  message?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "custom-trip-requests".
 */
export interface CustomTripRequest {
  id: number;
  status?: ('new' | 'in-review' | 'itinerary-sent' | 'confirmed' | 'closed') | null;
  visitDates?: string | null;
  travellers?: number | null;
  days?: number | null;
  interests?:
    | (
        | 'history'
        | 'culture'
        | 'food'
        | 'hiking'
        | 'adventure'
        | 'beaches'
        | 'nature'
        | 'nightlife'
        | 'art'
        | 'wellness'
      )[]
    | null;
  budget?: string | null;
  needs?: {
    accommodation?: boolean | null;
    transport?: boolean | null;
    airportTransfer?: boolean | null;
    privateGuide?: boolean | null;
  };
  notes?: string | null;
  contact: {
    name: string;
    email: string;
    phone?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "travel-service-requests".
 */
export interface TravelServiceRequest {
  id: number;
  status?: ('new' | 'contacted' | 'quoted' | 'confirmed' | 'closed') | null;
  serviceType: 'airport-transfer' | 'flights' | 'accommodation' | 'car-rental';
  summary?: string | null;
  contact: {
    name: string;
    email: string;
    phone?: string | null;
  };
  /**
   * The service-specific request details submitted by the customer.
   */
  details?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'destinations';
        value: number | Destination;
      } | null)
    | ({
        relationTo: 'experience-categories';
        value: number | ExperienceCategory;
      } | null)
    | ({
        relationTo: 'experiences';
        value: number | Experience;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'bookings';
        value: number | Booking;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'coupons';
        value: number | Coupon;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'newsletter-subscribers';
        value: number | NewsletterSubscriber;
      } | null)
    | ({
        relationTo: 'corporate-enquiries';
        value: number | CorporateEnquiry;
      } | null)
    | ({
        relationTo: 'custom-trip-requests';
        value: number | CustomTripRequest;
      } | null)
    | ({
        relationTo: 'travel-service-requests';
        value: number | TravelServiceRequest;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  category?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "destinations_select".
 */
export interface DestinationsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  region?: T;
  featured?: T;
  heroImage?: T;
  shortDescription?: T;
  whyVisit?: T;
  thingsToDo?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  bestTimeToVisit?: T;
  travelTips?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experience-categories_select".
 */
export interface ExperienceCategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  blurb?: T;
  icon?: T;
  image?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experiences_select".
 */
export interface ExperiencesSelect<T extends boolean = true> {
  title?: T;
  shortDescription?: T;
  description?: T;
  highlights?:
    | T
    | {
        text?: T;
        id?: T;
      };
  whoFor?: T;
  itinerary?:
    | T
    | {
        time?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  included?:
    | T
    | {
        text?: T;
        id?: T;
      };
  excluded?:
    | T
    | {
        text?: T;
        id?: T;
      };
  whatToBring?:
    | T
    | {
        text?: T;
        id?: T;
      };
  pricingStrategy?: T;
  priceFrom?: T;
  priceTiers?:
    | T
    | {
        minGuests?: T;
        maxGuests?: T;
        pricePerPerson?: T;
        requestQuote?: T;
        id?: T;
      };
  privatePrice?: T;
  visitorPricing?:
    | T
    | {
        enabled?: T;
        residentPrice?: T;
      };
  availabilityType?: T;
  weekdays?: T;
  includePublicHolidays?: T;
  minGuests?: T;
  maxGuests?: T;
  minNoticeHours?: T;
  maxAdvanceDays?: T;
  soldOut?: T;
  duration?: T;
  difficulty?: T;
  meetingPoint?: T;
  pickupInfo?: T;
  latitude?: T;
  longitude?: T;
  activityDetails?:
    | T
    | {
        distanceKm?: T;
        elevationM?: T;
        terrain?: T;
        fitnessNote?: T;
        equipmentProvided?: T;
        minimumAge?: T;
        mealIncluded?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  slug?: T;
  category?: T;
  destination?: T;
  badge?: T;
  featured?: T;
  rating?: T;
  reviewCount?: T;
  heroImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  title?: T;
  body?: T;
  rating?: T;
  authorName?: T;
  travellerType?: T;
  experience?: T;
  status?: T;
  verified?: T;
  bookingReference?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings_select".
 */
export interface BookingsSelect<T extends boolean = true> {
  reference?: T;
  status?: T;
  source?: T;
  experience?: T;
  customer?: T;
  departureDate?: T;
  adults?: T;
  children?: T;
  booker?:
    | T
    | {
        firstName?: T;
        lastName?: T;
        email?: T;
        phone?: T;
        country?: T;
        emergencyContact?: T;
      };
  pickup?: T;
  specialRequest?: T;
  dietary?: T;
  guests?:
    | T
    | {
        name?: T;
        category?: T;
        id?: T;
      };
  totalAmount?: T;
  paymentState?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  email?: T;
  phone?: T;
  country?: T;
  marketingOptIn?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons_select".
 */
export interface CouponsSelect<T extends boolean = true> {
  code?: T;
  type?: T;
  value?: T;
  appliesTo?: T;
  experiences?: T;
  events?: T;
  minOrder?: T;
  validFrom?: T;
  validTo?: T;
  maxUses?: T;
  usedCount?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  shortDescription?: T;
  description?: T;
  coverImage?: T;
  startsAt?: T;
  endsAt?: T;
  venue?: T;
  location?: T;
  destination?: T;
  about?: T;
  highlights?:
    | T
    | {
        text?: T;
        id?: T;
      };
  included?:
    | T
    | {
        text?: T;
        id?: T;
      };
  whatToExpect?: T;
  ticketTypes?:
    | T
    | {
        name?: T;
        price?: T;
        quantity?: T;
        saleStart?: T;
        saleEnd?: T;
        perOrderLimit?: T;
        soldOut?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  slug?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  coverImage?: T;
  body?:
    | T
    | {
        heading?: T;
        text?: T;
        id?: T;
      };
  content?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  slug?: T;
  category?: T;
  relatedDestination?: T;
  publishedAt?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  content?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscribers_select".
 */
export interface NewsletterSubscribersSelect<T extends boolean = true> {
  email?: T;
  source?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "corporate-enquiries_select".
 */
export interface CorporateEnquiriesSelect<T extends boolean = true> {
  pipelineStatus?: T;
  eventType?: T;
  organisation?: T;
  expectedGuests?: T;
  preferredDate?: T;
  durationDays?: T;
  location?: T;
  budget?: T;
  services?: T;
  contact?:
    | T
    | {
        name?: T;
        email?: T;
        phone?: T;
      };
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "custom-trip-requests_select".
 */
export interface CustomTripRequestsSelect<T extends boolean = true> {
  status?: T;
  visitDates?: T;
  travellers?: T;
  days?: T;
  interests?: T;
  budget?: T;
  needs?:
    | T
    | {
        accommodation?: T;
        transport?: T;
        airportTransfer?: T;
        privateGuide?: T;
      };
  notes?: T;
  contact?:
    | T
    | {
        name?: T;
        email?: T;
        phone?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "travel-service-requests_select".
 */
export interface TravelServiceRequestsSelect<T extends boolean = true> {
  status?: T;
  serviceType?: T;
  summary?: T;
  contact?:
    | T
    | {
        name?: T;
        email?: T;
        phone?: T;
      };
  details?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  tagline?: string | null;
  headline?: string | null;
  description?: string | null;
  primaryPhone?: string | null;
  altPhone?: string | null;
  /**
   * Digits only, for wa.me links.
   */
  whatsapp?: string | null;
  email?: string | null;
  address?: string | null;
  instagram?: string | null;
  tiktok?: string | null;
  linkedin?: string | null;
  facebook?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  tagline?: T;
  headline?: T;
  description?: T;
  primaryPhone?: T;
  altPhone?: T;
  whatsapp?: T;
  email?: T;
  address?: T;
  instagram?: T;
  tiktok?: T;
  linkedin?: T;
  facebook?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'experiences';
          value: number | Experience;
        } | null)
      | ({
          relationTo: 'events';
          value: number | Event;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null)
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}